### ISSUE TITLE
ivf-hnsw supports inner-product ?

### ISSUE THREAD

**Issue by scriptboy1990** [dbaranchuk/ivf-hnsw#5]
in faiss, hnsw  don't support inner product

**Comment by dbaranchuk** [comment]
Hi, it is a research code for the corresponding paper, where we did not consider a setup with inner-product. I suppose that it demands meaningful changes to support IP for the entire scheme with PQ compression.

If you need only hnsw supporting IP on original vectors out of the box, you may find it here: https://github.com/nmslib/nmslib. 

Moreover, as I can see, hnsw in faiss may support IP as well: each method in the HNSW class gets DistanceComputer structure. It seems that all you need is to implement your own DistanceComputer for inner product.
