### ISSUE TITLE
Hi, about d = || x - y_C - y_R ||^2 

### ISSUE THREAD

**Issue by 5ace** [dbaranchuk/ivf-hnsw#6]
hi buddy，
    Awesome code and article， i hava a question； In this code d = || x - y_C - y_R ||^2  turn to d = || x - y_C ||^2 - || y_C ||^2 + || y_C + y_R ||^2 - 2 * (x|y_R)； I want to know why not calc d in the way the same as in Faiss IVFPQ，first calc R = x - y_C on the fly, and then calc R and  y_R‘s l2 distance table,then find this table and Cumulative sum for then candidate indexed docs？In this way do not need store term2（ || y_C + y_R ||^2） save memory，and d is the exactly same as calc above || x - y_C ||^2 - || y_C ||^2 + || y_C + y_R ||^2 - 2 * (x|y_R).
  Thank you for helping me

**Comment by dbaranchuk** [comment]
Hi,

Thanks for your question. Let's look at FAISS decomposition:
d = || x - y_C ||^2 + || y_R ||^2 + 2 * (y_C|y_R) - 2 * (x|y_R)

Here, || y_R ||^2 + 2 * (y_C|y_R), indeed, can be precomputed and needs nlist * M * ksub storage. 

In our work, the coarse codebook contains 2^20 centroids => nlist=2^20. Let's assume that M=2^4 and ksub=2^8. As a result, we have to store 2^32 floats and hence 2^34 bytes ~= 16Gb. Our decomposition demands storing || y_C + y_R ||^2, which is just ~1Gb after the quantization.

**Comment by 5ace** [comment]
hi dbaranchuk，

Thanks for your reply. I think i have got your point, very make sense~  

Then I have another confusion about the purpose of the decomposition in your code and Faiss; At the very beginning i know ivfpq， people do the  d = || x - y_C - y_R ||^2 calculation as follow steps：

I. use x find the nearest y_C, the calculate residual x_R=x - y_C;
II. then use x_R precompute L2 distance table with y_R；
(see:https://hal.inria.fr/file/index/docid/514462/filename/paper_hal.pdf page 8 and 9 C. Search algorithm)

I am wondering what benefits can we get from the decomposition no matter in your code or Faiss code，save one vector minus step or turn distance table calculation from l2 to inner production?leading to higher recall or faster query performance?  

Bad english but also sincerely thanks  for this again ~ ^_^
