### ISSUE TITLE
how to get centroids file

### ISSUE THREAD

**Issue by flydt** [dbaranchuk/ivf-hnsw#8]
when test algorithm, we can use centroids file from google drive
but when I try to run kmeans algorithm on sift1b
and get centroids file
then can only pass siftsmall and sift1M test
but sift1b test always get result of 0.0 recall rate

how you can get google drive centroid file by bigann_learn.bvecs file ?

**Comment by dbaranchuk** [comment]
Hi,

Sorry for the late response. We just run a common k-means over bigann_learn.bvecs. The only modification is that we build HNSW graph on centroids for faster assignments and reconstruct it at each iteration. Nothing special.

**Comment by flydt** [comment]
got it, thank you
